version: '3.7'

services:
  fpm:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: laravel
    depends_on:
      - mysql



  vue:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: on-failure
    working_dir: /app
    volumes:
      - ./frontend/dist:/app/dist

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: laravel       
      MYSQL_ROOT_PASSWORD: laravel
      MYSQL_USER: laravel                 
      MYSQL_PASSWORD: laravel     
    volumes:
      - mysql-data:/var/lib/mysql      

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: laravel 
      PMA_PASSWORD: laravel
    ports:
      - "8081:80"    
    depends_on:
      - mysql        


  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always

    ports:
      - "80:80"
    volumes:
      - ./frontend/dist:/var/www/html/public 
    depends_on:
      - fpm
      - vue



volumes:
  mysql-data:
