services:

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}                 
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}     
    volumes:
      - mysql-data:/var/lib/mysql      

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: ${MYSQL_ROOT_NAME} 
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8081:80"    
    depends_on:
      - mysql        


  fpm:
    image: ghcr.io/danielfarag/project2-backend-laravel:latest
    restart: always
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      APP_DEBUG: true
      APP_ENV: local
    depends_on:
      - mysql

  vue:
    image: ghcr.io/danielfarag/project2-frontend-vue:latest
    restart: on-failure
    volumes:
      - frontend-dist:/app

  nginx:
    image: ghcr.io/danielfarag/project2-nginx:latest
    restart: always

    ports:
      - "80:80"
    volumes:
      - frontend-dist:/var/www/html/public 
    depends_on:
      - fpm
      - vue



volumes:
  mysql-data:
  frontend-dist:
