name: Build Backend & Frontend Images & Nginx Server
on:
    push:
        branches:
            - main

jobs:
    build_images:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: danielfarag
                password: ${{ secrets.AUTH_TOKEN }}

            - name: Build Backend Docker image
              run: docker build -t ghcr.io/danielfarag/project2-backend-laravel:latest ./backend
            
            - name: Push Backend Docker image to GitHub Container Registry
              run: docker push ghcr.io/danielfarag/project2-backend-laravel:latest
            

            - name: Build Frontend Docker image
              run: docker build -t ghcr.io/danielfarag/project2-frontend-vue:latest ./frontend
          
            - name: Push Frontend Docker image to GitHub Container Registry
              run: docker push ghcr.io/danielfarag/project2-frontend-vue:latest


            - name: Build Server Docker image
              run: docker build -t ghcr.io/danielfarag/project2-nginx:latest ./nginx
          
              
            - name: Push Server Docker image to GitHub Container Registry
              run: docker push ghcr.io/danielfarag/project2-nginx:latest



